ls:
  .dir: snake_case
  .*: snake_case
  .md: snake_case | regex:[0-9A-Z\-]+
  .txt: snake_case | kebab-case
  .yml: snake_case | kebab-case

  .:                       # Répertoires racine
    .*/:
      snakecase: true
    ignore:
      - 1_datasets/raw_data/**

ignore:
  - .git
  - .github
  - .vscode
  - venv
  - .ruff_cache
  - .pytest_cache
  - __pycache__
  - .ls-lint.yml
  - .markdownlint.yml


rules:
  some_rule: "true"
